### PR TITLE
Split project settings and app settings into separate classes

### LINKED ISSUE #708: Uploading a project with HTTP that has a different port throws an exception
This is caused by the server interrupting the thread that's loading the project when the port changes.

Stacktrace:

```java
edu.wpi.grip.core.exception.GripServerException: Could not stop Jetty server
	at edu.wpi.grip.core.http.GripServer.stop(GripServer.java:175)
	at edu.wpi.grip.core.http.GripServer.setPort(GripServer.java:216)
	at edu.wpi.grip.core.http.GripServer.settingsChanged(GripServer.java:234)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:95)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:154)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:80)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:76)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:119)
	at com.google.common.eventbus.EventBus.post(EventBus.java:215)
	at edu.wpi.grip.core.serialization.ProjectSettingsConverter.unmarshal(ProjectSettingsConverter.java:33)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1230)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1214)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1085)
	at edu.wpi.grip.core.serialization.Project.open(Project.java:115)
	at edu.wpi.grip.core.serialization.Project.open(Project.java:108)
	at edu.wpi.grip.core.http.HttpPipelineSwitcher.handleIfPassed(HttpPipelineSwitcher.java:46)
	at edu.wpi.grip.core.http.PedanticHandler.handle(PedanticHandler.java:53)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1257)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.doStop(QueuedThreadPool.java:161)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:143)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:161)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:73)
	at org.eclipse.jetty.server.Server.doStop(Server.java:476)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at edu.wpi.grip.core.http.GripServer.stop(GripServer.java:173)
	... 44 more
```

### PR DESCRIPTION
**Pull request by SamCarlberg**
Move port validation to GripServer and common CLI to the helper class
Make project settings reflect command-line port option
No longer serializes the server port. Use the command-line option or the settings dialog to set it. Fixes #708
Enable projects to be uploaded via HTTP in UI mode

### CODE REVIEW

**Comment by SamCarlberg** [comment]
Note this breaks backwards compatibility with saves created after the HTTP stuff was merged. Easy fix, just remove this line from the save file (it's at the bottom):

```xml
<serverPort> ... </serverPort>
```

Not a big problem since there's only been beta releases since the HTTP stuff was added.

File: core/src/main/java/edu/wpi/grip/core/http/GripServer.java [hunk 1]
```diff
@@ -100,6 +106,32 @@
    */
   public static final String DATA_PATH = ROOT_PATH + "/data";
 
+  /**
+   * The default port the server should run on.
+   */
+  public static final int DEFAULT_PORT = 8080;
```
Comment (SamCarlberg) [inline core/src/main/java/edu/wpi/grip/core/http/GripServer.java]: I think it's okay because we're hosting an HTTP server on the port. If it was something proprietary like a connection to a central server, it would be on a different port

Comment (AustinShalit) [inline core/src/main/java/edu/wpi/grip/core/http/GripServer.java]: Ummmmmmm............................. ok
