### PR TITLE
Fix Divide by Zero Error in CameraSource

### LINKED ISSUE #199: ArithmeticException: / by zero
What were the actions performed prior to this error appearing?

I added a webcam.  I'm using a USB webcam (Logitech 9000 Pro) on Windows 10 64-bit

Message: Camera Frame Grabber Thread crashed with uncaught exception

## System Info:

Property Name | Property 
 ----- | -----
javafx.version | 8.0.66
java.runtime.name | Java(TM) SE Runtime Environment
java.vm.version | 25.66-b17
java.vm.vendor | Oracle Corporation
java.vm.name | Java HotSpot(TM) 64-Bit Server VM
java.runtime.version | 1.8.0_66-b17
java.awt.graphicsenv | sun.awt.Win32GraphicsEnvironment
javafx.runtime.version | 8.0.66-b17
os.name | Windows 10
os.version | 10.0
os.arch | amd64
file.encoding | Cp1252
java.vm.info | mixed mode
java.version | 1.8.0_66
sun.arch.data.model | 64
sun.cpu.endian | little

## Stack Trace:
```java
java.lang.ArithmeticException: / by zero
	at edu.wpi.grip.core.sources.CameraSource.lambda$start$18(CameraSource.java:158)
	at java.lang.Thread.run(Thread.java:745)

```

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Closes #199

### CODE REVIEW

File: core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java [hunk 1]
```diff
@@ -154,8 +154,16 @@ public void start() throws IOException, IllegalStateException {
...
-                    long thisMoment = System.currentTimeMillis();
-                    frameRateOutputSocket.setValue(1000 / (thisMoment - lastFrame));
+
+                    final long thisMoment = System.currentTimeMillis();
+                    final long elapsedTime = thisMoment - lastFrame;
+                    if (elapsedTime == 0) {
+                        // This can actually happen: https://github.com/WPIRoboticsProjects/GRIP/issues/199
+                        frameRateOutputSocket.setValue(Double.NaN);
+                    } else {
+                        assert elapsedTime > 0 : "Time has run backwards!";
```
Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: You should not use `System.currentTimeMillis()` if going backwards is a problem.  `System.currentTimeMillis()` is non-monotonic, so backwards times are expected.

[`System.nanoTime()` is monotonically increasing](http://docs.oracle.com/javase/7/docs/api/java/lang/System.html#nanoTime()), so it would be a better choice

File: core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java [hunk 2]
```diff
@@ -154,8 +154,16 @@ public void start() throws IOException, IllegalStateException {
...
                     frameMat.copyTo(frameOutputSocket.getValue().get());
                     frameOutputSocket.setValue(frameOutputSocket.getValue().get());
-                    long thisMoment = System.currentTimeMillis();
-                    frameRateOutputSocket.setValue(1000 / (thisMoment - lastFrame));
+
+                    final long thisMoment = System.currentTimeMillis();
+                    final long elapsedTime = thisMoment - lastFrame;
+                    if (elapsedTime == 0) {
+                        // This can actually happen: https://github.com/WPIRoboticsProjects/GRIP/issues/199
+                        frameRateOutputSocket.setValue(Double.NaN);
```
Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: I think we should try not to have NaNs in the pipeline to avoid weird unexpected behavior.  A decent way to handle this would probably be to not change `frameRateOutputSocket` if essentially no time has elapsed, or to set it to 0.

These other options aren't technically mathematically correct, but I think it would be less suprising and less likely to break things.

File: core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java (hunk 1 above)
Comment (JLLeitschuh) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: :+1: Okay.

File: core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java (hunk 2 above)
Comment (JLLeitschuh) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: Brad offered a good suggestion. If for some reason the frame rate is zero then we should use the old value? Does this make sense?

Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: If the frame rate is zero?  Or the elapsed time?

Comment (bradamiller) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: Actually, I suggested that if the frame time is zero, then check the source and see why that is the case and how it can happen.

-- 
Brad Miller


On December 10, 2015 at 2:01:03 PM, Thomas Clark (notifications@github.com) wrote:

In core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java:

> @@ -154,8 +154,16 @@ public void start() throws IOException, IllegalStateException {
>   
>                      frameMat.copyTo(frameOutputSocket.getValue().get());
>                      frameOutputSocket.setValue(frameOutputSocket.getValue().get());
> -                    long thisMoment = System.currentTimeMillis();
> -                    frameRateOutputSocket.setValue(1000 / (thisMoment - lastFrame));
> +
> +                    final long thisMoment = System.currentTimeMillis();
> +                    final long elapsedTime = thisMoment - lastFrame;
> +                    if (elapsedTime == 0) {
> +                        // This can actually happen: https://github.com/WPIRoboticsProjects/GRIP/issues/199
> +                        frameRateOutputSocket.setValue(Double.NaN);
If the frame rate is zero? Or the elapsed time?

File: core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java [hunk 3]
```diff
@@ -154,8 +154,21 @@ public void start() throws IOException, IllegalStateException {
...
+                    if (elapsedTime == 0) {
+                        /* This can happen when using system.currentTimeMillis():
+                         * https://github.com/WPIRoboticsProjects/GRIP/issues/199
+                         * As such we use system.nanoTime().
+                         * However, we add an assertion to ensure this bug doesn't reappear.
+                         */
+                        assert elapsedTime != 0 : "The time between grabbing two frames was less than 1 nanosecond";
+                        frameRateOutputSocket.setValue(frameRateOutputSocket.getValue().get());
+                    } else {
+                        assert elapsedTime > 0 : "Time has run backwards!";
```
Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: Time does not run backwards with `System.nanoTime()` (and even if it did, an assertion would only catch that during development)

File: core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java [hunk 4]
```diff
@@ -154,8 +154,21 @@ public void start() throws IOException, IllegalStateException {
...
+
+                    final long thisMoment = System.nanoTime();
+                    final long elapsedTime = thisMoment - lastFrame;
+                    if (elapsedTime == 0) {
+                        /* This can happen when using system.currentTimeMillis():
+                         * https://github.com/WPIRoboticsProjects/GRIP/issues/199
+                         * As such we use system.nanoTime().
+                         * However, we add an assertion to ensure this bug doesn't reappear.
+                         */
+                        assert elapsedTime != 0 : "The time between grabbing two frames was less than 1 nanosecond";
```
Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: Why couldn't it occur with `System.nanoTime()`?  Monotonically increasing doesn't mean every call is greater than every previous call, it just never goes backwards.

This is also not an appropriate place to use an assertion, since we'd only see it during development.  So, if we're asserting something, it's a test to make sure it'll be like that before we ship with.  Since the thing you're asserting is a timing condition, passing one time does not mean it will always pass.

Comment (JLLeitschuh) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: What do you want me to do instead then? Leave it as a divide by zero error but using nano time instead? What do you think should be here?

File: core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java (hunk 3 above)
Comment (JLLeitschuh) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: I guess it doesn't make sense to test for that.

File: core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java (hunk 4 above)
Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: if (elapsedTime != 0) frameRateOutputSocket.setValue(1e12 / elapsedTime);

Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: And don't even check if time has run backwards

File: core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java (hunk 3 above)
Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: Right, but assertions are good because they'll tell us if we break something before we deploy.  `elapsedTime != 0` will tell us if an unlikely timing condition occurs, and since that would not happen consistently, the assertion would probably not catch it before deploying.

You're right that `assert elapsedTime > 0` should never happen, but I don't think that's even worth asserting.

Comment (PaulaRudy) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: I agree with Tom on this, but if it's already there I don't see any harm in keeping it.

File: core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java (hunk 4 above)
Comment (PaulaRudy) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: So I looked up using assertions in production code. Apparently this is an ongoing debate, but most people seem to agree with Tom that it should be avoided- instead of an assert, you should be handling errors explicitly- IE If you want to keep the test in, you should have something to handle it when it fails and you should be avoiding using "assert" in general. If you'd like to test this condition, re-writing it so that you don't use assert and the error is handled would be OK with me. But I think the easier option would be to simply take it out....

Comment (JLLeitschuh) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: I'll take it out

File: core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java [hunk 5]
```diff
@@ -154,8 +154,13 @@ public void start() throws IOException, IllegalStateException {
 
                     frameMat.copyTo(frameOutputSocket.getValue().get());
                     frameOutputSocket.setValue(frameOutputSocket.getValue().get());
-                    long thisMoment = System.currentTimeMillis();
-                    frameRateOutputSocket.setValue(1000 / (thisMoment - lastFrame));
+
+                    /*
+                     *
```
Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: Probably get rid of the empty comment things
