### PR TITLE
Fixes IP Cameras Hanging

### LINKED ISSUE #387: IP Camera Stream Crashing
Hello everyone,

I've been toying around with GRIP for the last week and I have to say it's an incredibly useful program, especially for Stronghold. However, our team has run into a problem where input from an Axis IP camera randomly crashes after a short time duration (anywhere from a few seconds to a few minutes). Sometimes, GRIP only loads up the first frame of the stream before freezing up. When I try to end the video stream and restart it, GRIP throws an exception (cannot stop IP camera stream) before crashing.

I know for a fact that the IP camera is working fine as I can view the video stream in a browser with the IP of the camera. I've tried restarting GRIP, uninstalling and reinstalling the stable release, restarting my computer, and using a completely different computer. I've attached my log and the GRIP exception error I mentioned earlier. 

Any help would be greatly appreciated.

TECHNICAL DETAILS:
OS: Windows 7
Release: Stable exe_x64
Camera: Axis M1013
Setup: Axis camera connected via ethernet to RoboRIO. Laptop running GRIP connected over Wifi to RoboRIO. Firewall disabled.
[GRIP_log.txt](https://github.com/WPIRoboticsProjects/GRIP/files/95169/GRIP_log.txt)
[Exception_Error.txt](https://github.com/WPIRoboticsProjects/GRIP/files/95170/Exception_Error.txt)

### LINKED ISSUE #390: CameraSource Error
IP Camera 10.13.25.23 Frame Grabber Thread crashed with uncaught exception

Stack Trace
```
java.lang.NullPointerException
	at edu.wpi.grip.core.sources.IPCameraFrameGrabber.grab(IPCameraFrameGrabber.java:137)
	at edu.wpi.grip.core.sources.CameraSource.lambda$start$18(CameraSource.java:200)
	at java.lang.Thread.run(Thread.java:745)
```
I also tried using this URL as well
http://10.13.25.23/mjpg/video.mjpg

### LINKED ISSUE #404: Axis IP Camera can be added, but no Image seen.
Using GRIP 1.0.0 on a x64 windows system. Can view webcam live view in Chrome. Putting in the IP address of the camera seems to add it in GRIP, but no image preview is available. Framerate is reported at zero. No downstream connected blocks have any visual output. 

 Exception thrown when deleting the camera in GRIP:

An event subscriber threw an exception
## Stack Trace:
```java
java.util.concurrent.TimeoutException: Unable to terminate video feed from IP Camera 10.17.36.12
	at edu.wpi.grip.core.sources.CameraSource.stop(CameraSource.java:279)
	at edu.wpi.grip.core.sources.CameraSource.onSourceRemovedEvent(CameraSource.java:312)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at edu.wpi.grip.ui.pipeline.source.SourceController.delete(SourceController.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1771)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:352)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:388)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:387)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

```
## System Info:

Property Name | Property 
 ----- | -----
GRIP Version | 1.0.0
java.version | 1.8.0_66
javafx.version | 8.0.66
os.name | Windows 7
os.version | 6.1
os.arch | amd64

This issue is most likely downstream of the actual problem. Any good way to go about debugging why the image preview is not displaying in GRIP to start?

### LINKED ISSUE #427: Unable to Terminate Video Feed after IP Camera feed freeze
I'm running an Axis 1013 IP Camera on the RoboRIO and passing it into GRIP on my laptop. After 10-60 seconds or so, the video stream will freeze. If I then try to delete the IP Camera source, GRIP throws the attached error. I've noticed that if I'm also running code on the robot the time to freeze increased to closer to 5 minutes between crashes.

An event subscriber threw an exception
## Stack Trace:
```java
java.util.concurrent.TimeoutException: Unable to terminate video feed from IP Camera 10.19.86.11
	at edu.wpi.grip.core.sources.CameraSource.stop(CameraSource.java:279)
	at edu.wpi.grip.core.sources.CameraSource.onSourceRemovedEvent(CameraSource.java:312)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at edu.wpi.grip.ui.pipeline.source.SourceController.delete(SourceController.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1771)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:352)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:388)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:387)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

```
## System Info:

Property Name | Property 
 ----- | -----
GRIP Version | 1.1.1
java.version | 1.8.0_66
javafx.version | 8.0.66
os.name | Windows 7
os.version | 6.1
os.arch | amd64

### LINKED ISSUE #436: Axis image freezes
IP camera  Axis M1011 image freezes in GRIP.  Camera stream can still be seen alive in a browser so it seems that it is a GRIP problem and not a camera problem.  Attempt to close the camera causes the timeout error.  Running GRIP on Windows 7 driver station PC.

An event subscriber threw an exception
## Stack Trace:
```java
java.util.concurrent.TimeoutException: Unable to terminate video feed from IP Camera 10.42.37.11
	at edu.wpi.grip.core.sources.CameraSource.stop(CameraSource.java:279)
	at edu.wpi.grip.core.sources.CameraSource.onSourceRemovedEvent(CameraSource.java:312)
	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at edu.wpi.grip.ui.pipeline.source.SourceController.delete(SourceController.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1771)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:352)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:388)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:387)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

```
## System Info:

Property Name | Property 
 ----- | -----
GRIP Version | 1.1.1
java.version | 1.8.0_66
javafx.version | 8.0.66
os.name | Windows 7
os.version | 6.1
os.arch | amd64

### PR DESCRIPTION
**Pull request by JLLeitschuh**
- The IPCameraFrameGrabber was stuck in an infinte loop
waiting for the rest of the image to arrive.
This was fixed by using a DataInputStream instead
 - An unexpected end of the stream would cause a null
pointer exception. Now throws an EOFException. #390

Closes #390
Closes #427
Closes #404
Closes #387
Closes #436
Related bytedeco/javacv#322

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
I'm merging this so that I can test in the pipeline rewrite PR.
I'm only going to have a Windows machine for a short period of time.

**Comment by ThomasJClark** [comment]
Test it first, then merge

File: core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java [hunk 1]
```diff
@@ -37,6 +38,19 @@
      * default path allows the Axis M1011 cameras used in FRC to work when only an IP address is supplied.
      */
     public final static String DEFAULT_IP_CAMERA_PATH = "/mjpg/video.mjpg";
+    private static final int
```
Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: Switch `final` and `static` for either here or the line above

File: core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java [hunk 2]
```diff
@@ -37,6 +38,19 @@
...
+            /**
+             * Connecting to a device can take the most time.
+             * This should have a little bit of leeway
+             */
+            IP_CAMERA_CONNECTION_TIMEOUT = 14;
```
Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: I would just do 5 for the read timeout.  In real life, people are gonna connect to axis cameras on an ethernet link, or maybe sometimes on the safe WiFi network.

The connection timeout should be unnecessary since we just retry the same connection when the timeout is up.  If there's a problem that can't be solved within the timeout (like the hostname lookup failed), it would fail immediately anyways.

IMO this is really self-documenting (too much documentation for simple things *is* a bad sign)

Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: Also, why aren't these defined in `IPCameraFrameGrabber`?

File: core/src/main/java/edu/wpi/grip/core/sources/IPCameraFrameGrabber.java [hunk 3]
```diff
@@ -180,18 +188,17 @@ public BufferedImage grabBufferedImage() throws IOException {
 
         if (c0 < 0) {
             //log.info("no content length returning null");
-            return null;
+            throw new EOFException("The camera stream ended unexpectedly");
```
Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/sources/IPCameraFrameGrabber.java]: Does this actually fix anything?  Have you tested what happens if this occurs?

**Comment by sciencewhiz** [comment]
With this patch, I was able to get two usb cameras working being streamed with mjpg-streamer over http. It was not reliable with the last release. I also tested with an AXIS camera

File: core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java (hunk 2 above)
Comment (JLLeitschuh) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: See the related issue that I opened bytedeco/javacv#322

File: core/src/main/java/edu/wpi/grip/core/sources/IPCameraFrameGrabber.java (hunk 3 above)
Comment (JLLeitschuh) [inline core/src/main/java/edu/wpi/grip/core/sources/IPCameraFrameGrabber.java]: This fixes #390

**Comment by JLLeitschuh** [comment]
@sciencewhiz Glad to hear it!

File: core/src/main/java/edu/wpi/grip/core/sources/IPCameraFrameGrabber.java (hunk 3 above)
Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/sources/IPCameraFrameGrabber.java]: Ok, but what happens? Will it try again, or show an error?

File: core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java (hunk 2 above)
Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: Ok? That didn't really answer my questions

File: core/src/main/java/edu/wpi/grip/core/sources/IPCameraFrameGrabber.java (hunk 3 above)
Comment (JLLeitschuh) [inline core/src/main/java/edu/wpi/grip/core/sources/IPCameraFrameGrabber.java]: Both

File: core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java (hunk 2 above)
Comment (JLLeitschuh) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: > The connection timeout should be unnecessary since we just retry the same connection when the timeout is up. If there's a problem that can't be solved within the timeout (like the hostname lookup failed), it would fail immediately anyways.

If we don't have the connection timeout it doesn't give up immediately. It usually hangs for a long time instead. If you try to kill the service while it's trying to connect you cant.


> Also, why aren't these defined in `IPCameraFrameGrabber`?

See the related issue that I opened bytedeco/javacv#322
Because everything relating to the input to the IPCameraFrameGrabber should be in the Camera, not in the logic that runs the camera.

File: core/src/main/java/edu/wpi/grip/core/sources/IPCameraFrameGrabber.java (hunk 3 above)
Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/sources/IPCameraFrameGrabber.java]: ok

**Comment by cyberx696** [comment]
After building the latest source code, I still encounter the issue where the IP camera throws an exception and (in my case) don't even start. I've tried them in the v1.1.1 release too, but the same error occurs.
[GRIP.log.txt](https://github.com/WPIRoboticsProjects/GRIP/files/120509/GRIP.log.txt)

 

TECHNICAL DETAILS:
OS: Windows 7
Release: Stable exe_x64
Camera: Axis M1013, Panasonic VP104
Setup: Axis camera connected via ethernet to RoboRIO. Laptop running GRIP connected over Wifi to RoboRIO. 

The first one (Axis M1013) crashed with a camera source error where it failed to grab the image. I tested this URL (http://10.6.96.10/cgi-bin/mjpeg) in a browser but it failed in GRIP. The error is below.

> Feb 06, 2016 3:59:52 PM edu.wpi.grip.core.sources.CameraSource$1 run
WARNING: Failed to grab image
org.bytedeco.javacv.FrameGrabber$Exception: The camera stream ended unexpectedly
	at edu.wpi.grip.core.sources.IPCameraFrameGrabber.grab(IPCameraFrameGrabber.java:137)
	at edu.wpi.grip.core.sources.CameraSource$1.run(CameraSource.java:227)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:100)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: The camera stream ended unexpectedly
	at edu.wpi.grip.core.sources.IPCameraFrameGrabber.readImage(IPCameraFrameGrabber.java:177)
	at edu.wpi.grip.core.sources.IPCameraFrameGrabber.grab(IPCameraFrameGrabber.java:130)
	... 4 more


The second camera I tested (a Panasonic V104) also failed to start. I tested two different URLs (http://10.6.96.21/axis-cgi/mjpg/video.cgi?camera=1&resolution=320x240, http://10.6.96.21/mjpg/1/video.mjpg)  but both returned the following stack trace:

> org.bytedeco.javacv.FrameGrabber$Exception: Server returned HTTP response code: 401 for URL: http://10.6.96.21/axis-cgi/mjpg/video.cgi?camera=1&resolution=320x240
	at edu.wpi.grip.core.sources.IPCameraFrameGrabber.start(IPCameraFrameGrabber.java:99)
	at edu.wpi.grip.core.sources.CameraSource$1.startUp(CameraSource.java:210)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:54)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:100)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: http://10.6.96.21/axis-cgi/mjpg/video.cgi?camera=1&resolution=320x240
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at edu.wpi.grip.core.sources.IPCameraFrameGrabber.start(IPCameraFrameGrabber.java:96)
	... 4 more

I'm not sure why both times GRIP failed to load the video stream as they work perfectly fine in a browser. Some things I've tried include disabling my firewall/antivirus and disabling logins on both the cameras.

Any help would be appreciated.

**Comment by ThomasJClark** [comment]
> The first one (Axis M1013) crashed with a camera source error where it failed to grab the image. I tested this URL (http://10.6.96.10/cgi-bin/mjpeg) in a browser but it failed in GRIP. The error is below.

What was the actual URL you put into GRIP?  For axis cameras it should basically just be the camera's IP address.

> The second camera I tested (a Panasonic V104) also failed to start. I tested two different URLs (http://10.6.96.21/axis-cgi/mjpg/video.cgi?camera=1&resolution=320x240, http://10.6.96.21/mjpg/1/video.mjpg) but both returned the following stack trace:

Is the camera password protected?  HTTP 401 means not authorized.

**Comment by cyberx696** [comment]
For the Axis camera, I tried both the URL above and its IP. Both returned the same error.

For the second camera, I double-checked to make sure that there were no authentication settings blocking unauthorized users from accessing the camera. After trying to connect again to it in GRIP, I got the following error:

`org.bytedeco.javacv.FrameGrabber$Exception: The camera stream ended unexpectedly
	at edu.wpi.grip.core.sources.IPCameraFrameGrabber.grab(IPCameraFrameGrabber.java:137)
	at edu.wpi.grip.core.sources.CameraSource$1.run(CameraSource.java:227)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:100)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: The camera stream ended unexpectedly
	at edu.wpi.grip.core.sources.IPCameraFrameGrabber.readImage(IPCameraFrameGrabber.java:177)
	at edu.wpi.grip.core.sources.IPCameraFrameGrabber.grab(IPCameraFrameGrabber.java:130)
	... 4 more
`

**Comment by cyberx696** [comment]
@ThomasJClark 
It still fails to even open the stream with the new radio. Please let me know if you have any idea what the issue what might be.

Here's the latest stack tracer, with v1.2:
org.bytedeco.javacv.FrameGrabber$Exception: The camera stream ended unexpectedly
	at edu.wpi.grip.core.sources.IPCameraFrameGrabber.grab(IPCameraFrameGrabber.java:137)
	at edu.wpi.grip.core.sources.CameraSource$1.run(CameraSource.java:227)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:100)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: The camera stream ended unexpectedly
	at edu.wpi.grip.core.sources.IPCameraFrameGrabber.readImage(IPCameraFrameGrabber.java:177)
	at edu.wpi.grip.core.sources.IPCameraFrameGrabber.grab(IPCameraFrameGrabber.java:130)
	... 4 more
