### PR TITLE
Fix connections not positioning correctly when loading project

### LINKED ISSUE #321: Connections are positioned weirdly
In the dependency injection refactor, for some reason the transform invalidation and synchronization stuff that keeps the connections correctly positions was rewritten.  As a result of this, connections are incorrectly positioned when a new project is opened, as shown below.  In addition, connections flicker when they move, since that's done using `Platform.runLater` and some custom functions instead of `PlatformImpl.runAndWait`.

s

### PR DESCRIPTION
**Pull request by ThomasJClark**
Also connections flickering when moving.

Closes #321

Before:
before

After:
after

### CODE REVIEW

File: ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java [hunk 1]
```diff
@@ -227,7 +222,7 @@ private void addConnectionView(Connection connection) {
 
     @Subscribe
     public void onSourceAdded(SourceAddedEvent event) {
-        platform.runAsSoonAsPossible(() -> {
+        PlatformImpl.runAndWait(() -> {
```
Comment (JLLeitschuh) [inline ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java]: Deadlock prone.

File: ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java [hunk 2]
```diff
@@ -235,7 +230,7 @@ public void onSourceAdded(SourceAddedEvent event) {
 
     @Subscribe
     public void onSourceRemoved(SourceRemovedEvent event) {
-        platform.runAsSoonAsPossible(() -> {
+        PlatformImpl.runAndWait(() -> {
```
Comment (JLLeitschuh) [inline ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java]: Deadlock prone

File: ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java [hunk 3]
```diff
@@ -245,7 +240,7 @@ public void onSourceRemoved(SourceRemovedEvent event) {
     @Subscribe
     public void onStepAdded(StepAddedEvent event) {
         // Add a new view to the pipeline for the step that was added
-        platform.runAsSoonAsPossible(() -> {
+        PlatformImpl.runAndWait(() -> {
```
Comment (JLLeitschuh) [inline ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java]: Deadlock prone

File: ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java [hunk 4]
```diff
@@ -259,7 +254,7 @@ public void onStepAdded(StepAddedEvent event) {
     @Subscribe
     public void onStepRemoved(StepRemovedEvent event) {
         // Remove the control that corresponds with the step that was removed
-        platform.runAsSoonAsPossible(() -> {
+        PlatformImpl.runAndWait(() -> {
```
Comment (JLLeitschuh) [inline ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java]: Deadlock prone.

File: ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java [hunk 5]
```diff
@@ -269,7 +264,7 @@ public void onStepRemoved(StepRemovedEvent event) {
 
     @Subscribe
     public void onStepMoved(StepMovedEvent event) {
-        platform.runAsSoonAsPossible(() -> {
+        PlatformImpl.runAndWait(() -> {
```
Comment (JLLeitschuh) [inline ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java]: Deadlock prone

File: ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java [hunk 6]
```diff
@@ -278,13 +273,13 @@ public void onStepMoved(StepMovedEvent event) {
...
         // Add the new connection view
-        platform.runAsSoonAsPossible(() -> addConnectionView(event.getConnection()));
+        addConnectionView(event.getConnection());
     }
 
     @Subscribe
     public void onConnectionRemoved(ConnectionRemovedEvent event) {
         // Remove the control that corresponds with the connection that was removed
-        platform.runAsSoonAsPossible(() -> {
+        PlatformImpl.runAndWait(() -> {
```
Comment (JLLeitschuh) [inline ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java]: Deadlock prone

Comment (ThomasJClark) [inline ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java]: I don't think this should deadlock, and believe I've read all the relevant literature on `runAndWait()`.  Any evidence to back this up?

Comment (JLLeitschuh) [inline ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java]: Yes, that's why I created `runAsSoonAsPossible`.
I had major deadlocking problems when writing dependency injection. The only 100% deadlock free way of doing this is, using `Platform.runLater`.

Comment (ThomasJClark) [inline ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java]: Ok, but I really don't believe this code deadlocks.  Do you have evidence that it does or not?

Comment (JLLeitschuh) [inline ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java]: I don't have evidence that it doesn't work in this case no.
What I do know is that `runAndWait` can deadlock the javafx thread on the event bus because another thread is waiting on the javafx thread to run and the javafx thread is trying to run an event.

Basically, I don't trust `runAndWait` at all. I think it is a nasty hack around a problem that is a simple drawing problem. Try invalidating the view and triggering a redraw instead.

Comment (ThomasJClark) [inline ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java]: We *want* it to wait on the JavaFX thread, otherwise there's flickering.

> Basically, I don't trust runAndWait at all. 

I think that's a bit unfair. `runAndWait` would only deadlock if we post an event inside of it. It's totally appropriate to use for cases where we're only manipulating JavaFX components (not grip objects) from an arbitrary thread and we want it to complete atomically.

There's nothing untrustworthy about it, it just doesn't interact well with the unusual behavior of `eventBus.post()`.

Trust me, I've tested this code in every possible situation, and I've spent some time reasoning about how this needs to work. Doing it this way removes some annoying flickering, and I think that will have a positive impact on users trying this for the first time.

Comment (JLLeitschuh) [inline ui/src/main/java/edu/wpi/grip/ui/pipeline/PipelineController.java]: Okay, can you leave comments on the lines saying that this is intentional, and that it won't break anything. And also include that there should be no events posted inside of the blocks of code.
