### PR TITLE
Check for number of channels in threshold operations

### LINKED ISSUE #178: OpenCV inRange is Segfault Prone; Create 'safeInRange' method
Since OpenCV's `inRange` method is prone to segfaulting with the wrong input it should be avoided. Instead, `inRange` should be wrapped in a helper function that provides certain safety guarantees to ensure that a segfault is not possible.

### PR DESCRIPTION
**Pull request by ThomasJClark**
inRange segfaults if we give it three channels of ranges but a single
channel image.  Throwing an IllegalArgumentException is not ideal, but
it's better than segfaulting.

Closes #178
Related #250

### CODE REVIEW

File: core/src/main/java/edu/wpi/grip/core/operations/composite/HSVThresholdOperation.java [hunk 1]
```diff
@@ -22,7 +22,7 @@
  */
 public class HSVThresholdOperation extends ThresholdOperation {
 
-    private static final Logger logger =  Logger.getLogger(HSVThresholdOperation.class.getName());
+    private static final Logger logger = Logger.getLogger(HSVThresholdOperation.class.getName());
```
Comment (JLLeitschuh) [inline core/src/main/java/edu/wpi/grip/core/operations/composite/HSVThresholdOperation.java]: Why?

File: core/src/main/java/edu/wpi/grip/core/operations/composite/RGBThresholdOperation.java [hunk 2]
```diff
@@ -15,7 +15,7 @@
  */
 public class RGBThresholdOperation extends ThresholdOperation {
 
-    private static final Logger logger =  Logger.getLogger(RGBThresholdOperation.class.getName());
+    private static final Logger logger = Logger.getLogger(RGBThresholdOperation.class.getName());
```
Comment (JLLeitschuh) [inline core/src/main/java/edu/wpi/grip/core/operations/composite/RGBThresholdOperation.java]: Why?

File: core/src/main/java/edu/wpi/grip/core/operations/composite/HSLThresholdOperation.java [hunk 3]
```diff
@@ -20,7 +20,7 @@
  * An {@link edu.wpi.grip.core.Operation} that converts a color image into a binary image based on the HSL threshold ranges
  */
 public class HSLThresholdOperation extends ThresholdOperation {
-    private static final Logger logger =  Logger.getLogger(HSLThresholdOperation.class.getName());
+    private static final Logger logger = Logger.getLogger(HSLThresholdOperation.class.getName());
```
Comment (JLLeitschuh) [inline core/src/main/java/edu/wpi/grip/core/operations/composite/HSLThresholdOperation.java]: Why?

File: core/src/main/java/edu/wpi/grip/core/operations/composite/RGBThresholdOperation.java [hunk 4]
```diff
@@ -65,6 +65,10 @@ public void perform(InputSocket<?>[] inputs, OutputSocket<?>[] outputs, Optional
         final List<Number> channel2 = ((InputSocket<List<Number>>) inputs[2]).getValue().get();
         final List<Number> channel3 = ((InputSocket<List<Number>>) inputs[3]).getValue().get();
 
+        if (input.channels() != 3) {
+            throw new IllegalArgumentException("RGB Threshold needs a 3-channel input");
+        }
```
Comment (JLLeitschuh) [inline core/src/main/java/edu/wpi/grip/core/operations/composite/RGBThresholdOperation.java]: Sure!

File: core/src/main/java/edu/wpi/grip/core/operations/composite/HSLThresholdOperation.java [hunk 5]
```diff
@@ -64,6 +64,10 @@ public void perform(InputSocket<?>[] inputs, OutputSocket<?>[] outputs, Optional
         final List<Number> channel2 = ((InputSocket<List<Number>>) inputs[2]).getValue().get();
         final List<Number> channel3 = ((InputSocket<List<Number>>) inputs[3]).getValue().get();
 
+        if (input.channels() != 3) {
+            throw new IllegalArgumentException("HSL Threshold needs a 3-channel input");
+        }
```
Comment (JLLeitschuh) [inline core/src/main/java/edu/wpi/grip/core/operations/composite/HSLThresholdOperation.java]: Sure!

File: core/src/main/java/edu/wpi/grip/core/operations/composite/RGBThresholdOperation.java (hunk 2 above)
Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/operations/composite/RGBThresholdOperation.java]: Because autoformat (there was an extra space before, IntelliJ automatically removed it)
