### PR TITLE
Fix #695

### LINKED ISSUE #695: Ubuntu 16.10: Cancel on error quits GRIP UI
NullPointerException when removing objects from pipeline. Two case scenarios:

Case 1:
   -Setup pipeline, connect some steps
   -Start deleting steps from pipeline that are used by other steps (slowly)
   -Receive an error about a NullPointerException from the pipeline
   -Hit cancel on the message, then the UI quits out unexpectedly

Case 2:
   -Start up Ubuntu without a camera connected (or unplug all cameras from ubuntu before launching GRIP)
   -Add camera to GRIP without physical connection
   -Verify that the Camera is 'connected' using the flashing red 'X' next to the step in the sources pane
   -Remove camera from the pipeline, UI crashes (there might be another UI error window that displays, but I have not yet confirmed that)

Device: mid-2015 MacBook Pro
Type: Virtual Machine, guest
OS: Ubuntu 16.10 x64

VirtualBox configuration:
RAM: 8GB
CPU: i7 2.2GHz (quad-core, not default)
PAX/NE enabled (not default)
VRAM: 128MB (not default)
1 Screen (default)
HiDPI (2.0)
Network: NAT (default)
Audio: ICH AC97 (not default)
Execution Cap: 100% (default)
[VirtualBox Hard Drive download](https://drive.google.com/open?id=0B86Py5WkgumYVjUxSTM0QXlNTGc)

### PR DESCRIPTION
**Pull request by SamCarlberg**
Closes #695 

695 brought up two problems:

1. Removing a step with connections from the pipeline would cause an exception to be thrown; and  
2. Removing a failing camera source would also cause an exception (unrelated to point 1)

### CODE REVIEW

**Comment by SamCarlberg** [comment]
@JLLeitschuh Can you take a look a the CameraSourceTest to make sure I didn't screw it up?

File: core/src/test/java/edu/wpi/grip/core/sources/CameraSourceTest.java [hunk 1]
```diff
@@ -193,18 +200,24 @@ public FrameGrabber create(String addressProperty) throws MalformedURLException
...
     waiter3.await();
-    try {
-      source.stopAndAwait();
-      fail("This should have failed");
-    } catch (IllegalStateException e) {
-      assertThat(e.getCause()).isNotNull();
-      assertThat(e.getCause().getCause()).isNotNull();
-      assertThat(e.getCause().getCause()).hasMessage(GRABBER_START_MESSAGE);
-    }
+    source.stopAndAwait();
```
Comment (JLLeitschuh) [inline core/src/test/java/edu/wpi/grip/core/sources/CameraSourceTest.java]: Stop and await should fail because starting throws an exception. Right?

Comment (SamCarlberg) [inline core/src/test/java/edu/wpi/grip/core/sources/CameraSourceTest.java]: Uh, that's what this PR is fixing.

File: core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java [hunk 2]
```diff
@@ -285,12 +285,24 @@ public CameraSource stopAsync() {
...
 
   @Override
   public void stopAndAwait(long timeout, TimeUnit unit) throws TimeoutException {
-    stopAsync().cameraService.stopAndAwait(timeout, unit);
+    try {
+      stopAsync().cameraService.stopAndAwait(timeout, unit);
+    } catch (IllegalStateException e) {
+      if (!cameraService.state().equals(State.FAILED)) {
+        throw e;
+      }
```
Comment (SamCarlberg) [inline core/src/main/java/edu/wpi/grip/core/sources/CameraSource.java]: It means that the service crashed while running, or an exception was thrown on startup (e.g. the webcam doesn't exist or isn't available). All this does is stop if it's in terminal state (TERMINATED or FAILED), instead of throwing another exception if startup failed
