### PR TITLE
Fixes various Deployment UI Issues

### LINKED ISSUE #301: ParseException: Unparseable number: in any spinner input field
What were the actions performed prior to this error appearing?

1. Create any step with a number input box, (for example resize)
2. Enter a character in the spinner box.
3. Click the up or down buttons on the same spinner
4. Exception happens that can not be cleared.

Message: Thread[JavaFX Application Thread,5,main] threw an exception

## System Info:

Property Name | Property 
 ----- | -----
GRIP Version | 1.0.0-rc1
javafx.version | 8.0.66
java.runtime.name | Java(TM) SE Runtime Environment
java.vm.version | 25.66-b17
java.vm.vendor | Oracle Corporation
java.vm.name | Java HotSpot(TM) 64-Bit Server VM
java.runtime.version | 1.8.0_66-b17
java.awt.graphicsenv | sun.awt.CGraphicsEnvironment
javafx.runtime.version | 8.0.66-b17
os.name | Mac OS X
os.version | 10.11.2
os.arch | x86_64
file.encoding | UTF-8
java.vm.info | mixed mode
java.version | 1.8.0_66
sun.arch.data.model | 64
sun.cpu.endian | little

## Stack Trace:
```java
java.lang.RuntimeException: java.text.ParseException: Unparseable number: "d"
	at javafx.scene.control.SpinnerValueFactory$DoubleSpinnerValueFactory$1.fromString(SpinnerValueFactory.java:724)
	at javafx.scene.control.SpinnerValueFactory$DoubleSpinnerValueFactory$1.fromString(SpinnerValueFactory.java:696)
	at edu.wpi.grip.ui.pipeline.input.NumberSpinnerInputSocketController.commitEditorText(NumberSpinnerInputSocketController.java:91)
	at edu.wpi.grip.ui.pipeline.input.NumberSpinnerInputSocketController.lambda$initialize$79(NumberSpinnerInputSocketController.java:62)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
	at javafx.scene.Node$FocusedProperty.notifyListeners(Node.java:7718)
	at javafx.scene.Node.setFocused(Node.java:7771)
	at javafx.scene.Scene$KeyHandler.setWindowFocused(Scene.java:3932)
	at javafx.scene.Scene$KeyHandler.lambda$new$11(Scene.java:3954)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyBooleanWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:178)
	at javafx.beans.property.ReadOnlyBooleanWrapper$ReadOnlyPropertyImpl.access$100(ReadOnlyBooleanWrapper.java:148)
	at javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:144)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setFocused(Window.java:439)
	at com.sun.javafx.stage.WindowPeerListener.changedFocused(WindowPeerListener.java:59)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:100)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$423(GlassWindowEventHandler.java:150)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:148)
	at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1266)
	at com.sun.glass.ui.Window.notifyFocus(Window.java:1245)
	at com.sun.glass.ui.mac.MacWindow._setVisible(Native Method)
	at com.sun.glass.ui.Window.setVisible(Window.java:625)
	at com.sun.javafx.tk.quantum.WindowStage.lambda$setVisible$390(WindowStage.java:499)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithRenderLock(QuantumToolkit.java:407)
	at com.sun.javafx.tk.quantum.WindowStage.setVisible(WindowStage.java:495)
	at javafx.stage.Window$9.invalidated(Window.java:869)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at javafx.stage.Stage.showAndWait(Stage.java:472)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:341)
	at edu.wpi.grip.ui.Main.lambda$onUnexpectedThrowableEvent$39(Main.java:83)
	at com.sun.javafx.application.PlatformImpl.runAndWait(PlatformImpl.java:317)
	at com.sun.javafx.application.PlatformImpl.runAndWait(PlatformImpl.java:307)
	at edu.wpi.grip.ui.Main.onUnexpectedThrowableEvent(Main.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at edu.wpi.grip.core.GRIPCoreModule.onThreadException(GRIPCoreModule.java:124)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at com.sun.glass.ui.Application.reportException(Application.java:453)
Caused by: java.text.ParseException: Unparseable number: "d"
	at java.text.NumberFormat.parse(NumberFormat.java:385)
	at javafx.scene.control.SpinnerValueFactory$DoubleSpinnerValueFactory$1.fromString(SpinnerValueFactory.java:722)
	... 58 more

```

### PR DESCRIPTION
**Pull request by JLLeitschuh**
- The deploy UI resizing when labels change size
 - Adds a label to the play button in deploying
 - Deploying now uses project defaults
 - Ensure changing the team number will commit that value

Closes #301 #299 #282 #258

### CODE REVIEW

File: ui/src/main/java/edu/wpi/grip/ui/deployment/FRCAdvancedDeploymentOptionsController.java [hunk 1]
```diff
@@ -32,11 +34,13 @@ FRCAdvancedDeploymentOptionsController create(
 
     @Inject
     FRCAdvancedDeploymentOptionsController(DeployedInstanceManager.Factory deployedInstanceManagerFactor,
+                                           Pipeline pipeline,
                                            @Assisted Consumer<DeployedInstanceManager> onDeployCallback,
                                            @Assisted("stdOut") Supplier<OutputStream> stdOut,
                                            @Assisted("stdErr") Supplier<OutputStream> stdErr) {
         super("FRC Advanced", onDeployCallback);
         this.deployedInstanceManagerFactor = deployedInstanceManagerFactor;
+        this.projectAddress = pipeline.getProjectSettings().computeNetworkTablesServer();
```
Comment (ThomasJClark) [inline ui/src/main/java/edu/wpi/grip/ui/deployment/FRCAdvancedDeploymentOptionsController.java]: Cool, but what if a user wants to override this?  They'd have to change this every time.  We should have `robotAddress` and `networkTablesAddress` as two different project settings

Comment (JLLeitschuh) [inline ui/src/main/java/edu/wpi/grip/ui/deployment/FRCAdvancedDeploymentOptionsController.java]: We already stated that we are keeping the accordion.
In case you've forgotten, here's the discussion where we made this decision: https://github.com/WPIRoboticsProjects/GRIP/issues/258

Comment (ThomasJClark) [inline ui/src/main/java/edu/wpi/grip/ui/deployment/FRCAdvancedDeploymentOptionsController.java]: It was just a suggestion.  We can go over it later.  Either way, this should still be its own project setting.

Comment (JLLeitschuh) [inline ui/src/main/java/edu/wpi/grip/ui/deployment/FRCAdvancedDeploymentOptionsController.java]: Wouldn't it be `network protocol address` and `deploy address`?

Comment (ThomasJClark) [inline ui/src/main/java/edu/wpi/grip/ui/deployment/FRCAdvancedDeploymentOptionsController.java]: Sure, whatever seems best

**Comment by JLLeitschuh** [comment]
Okay, I updated this so that there is a separate field for deploy address.

**Comment by JLLeitschuh** [comment]
Can this be merged before I send out the release candidate?

**Comment by ThomasJClark** [comment]
The display name for "Network Protocol Server Address" should definitely just be "NetworkTables Server Address" until we support more protocols.

Display names won't affect serialization backwards compatibility, and I seriously think this will confuse FRC teams.

Other than that, this looks good.

**Comment by JLLeitschuh** [comment]
Okay, I'll fix that.

**Comment by JLLeitschuh** [comment]
Off Topic: I'm going to bed as soon as the release candidate is uploaded.

File: core/src/main/java/edu/wpi/grip/core/settings/ProjectSettings.java [hunk 2]
```diff
@@ -27,9 +27,13 @@
...
 
-    @Setting(label = "NetworkTables Server", description = "The host that runs the NetworkTables server.  If not " +
-            "specified but NetworkTables is enabled, the hostname is derived from the team number.")
-    private String networkTablesServer = "";
+    @Setting(label = "NetworkTables Server Address", description = "The host that runs the Network Protocol server.  If not " +
+            "specified and Network Tables is specified as the protocol, the hostname is derived from the team number.")
+    private String networkProtocolServerAddress = "";
+
+    @Setting(label = "Deploy Address", description = "The remote host that grip should be remotely deployed to. If not " +
+            "specified and Network Tables is specified as the protocol, the hostname is derived from the team number.")
```
Comment (ThomasJClark) [inline core/src/main/java/edu/wpi/grip/core/settings/ProjectSettings.java]: > "and Network Tables is specified as the protocol"

This should be changed do "and GRIP is deployed" or something.
