### PR TITLE
Initialize sources loaded from save file before firing event

### LINKED ISSUE #913: Video file sources loaded from save files do not have controls
**Describe the bug**  
A video file source that is loaded from a save file does not have the play/pause button and scrubber controls.

**To Reproduce**  
1. Add a new video file source
2. Save the project
3. Load the saved project

**Expected behavior**  
Video files sources should always have controls

### PR DESCRIPTION
**Pull request by SamCarlberg**
Fixes a problem with video file sources loaded from a save file not having play/pause and scrubber controls

Closes #913

### CODE REVIEW

File: core/src/main/java/edu/wpi/grip/core/serialization/SourceConverter.java [hunk 1]
```diff
@@ -54,16 +54,16 @@ public Object unmarshal(HierarchicalStreamReader reader, UnmarshallingContext co
...
-      eventBus.post(new SourceAddedEvent(source));
-
       // Now that the source has been added it needs to be initialized
       // We do it safely here in case the source has changed in some way out
       // of our control. For example, if a webcam is no longer available.
       source.initializeSafely();
 
+      // Instead of returning the source, post it to the event bus so both the core and GUI
+      // classes know it
+      // exists.
```
Comment (JLLeitschuh) [inline core/src/main/java/edu/wpi/grip/core/serialization/SourceConverter.java]: Formatting.

Comment (SamCarlberg) [reply core/src/main/java/edu/wpi/grip/core/serialization/SourceConverter.java]: Heh. I moved the `initializeSafely()` line and comment, but the diff shows the event post lines changed instead.
